### ISSUE TITLE
User steam does not exist

### ISSUE THREAD

**Issue by Lagicrus** [thijsvanloef/palworld-server-docker#26] opened 2024-01-21 14:23 UTC
**Describe the bug**
When creating the docker container for the first time, when it runs usermod, the user and group do not exist

**Screenshots**
2024-01-21 14:21:16.248397+00:00Executing usermod...
2024-01-21 14:21:16.253073+00:00usermod: user 'steam' does not exist
2024-01-21 14:21:16.255149+00:00groupmod: group 'steam' does not exist
2024-01-21 14:21:16.257785+00:00chown: invalid user: 'steam:steam'
2024-01-21 14:21:16.259683+00:00su: user steam does not exist or the user entry does not contain all the required fields

**Desktop (please complete the following information):**
 - OS: TrueNas
 - Version: 0.8.0

**Comment by thijsvanloef** [comment] 2024-01-21 14:32
Could you provide the docker-compose.yml you've used for deployment?

**Comment by Lagicrus** [comment] 2024-01-21 14:37
enviroment:
- PORT=8211
- PLAYERS=6
- MULTITHREADING=FALSE
- PUID=568
- PGID=568

**Comment by thijsvanloef** [comment] 2024-01-21 15:46
Could you share the entire docker-compose.yml? 

My first suspicions are that the docker container does not run well on freeBSD based operating systems

**Comment by Lagicrus** [comment] 2024-01-21 16:16
I don't have a docker-compose.yml per say, instead I input the various configurations into the UI which then gets passed to it.
I'm also on TrueNas Scale which I believe is Debian based, as I have other docker containers running on here with little to no issue.

**Comment by thijsvanloef** [comment] 2024-01-21 17:35
Ah my bad, assumed you ran TrueNAS core. Sadly I'm not able to reproduce it, as I am only able to test on Windows and Debian. 
Hopefully someone else would be able to help you in this matter

**Comment by xHyperElectric** [comment] 2024-01-22 23:14
@Lagicrus I am currently running this image successfully on TrueNAS Scale via TrueChart's "custom-app". I have made a thread in the [TrueCharts Discord](https://discord.com/invite/Ax9ZgzKx9t) detailing my settings to get it running. Feel free to ask any questions you may have. [Here is a link to the start of the Discord Thread](https://discord.com/channels/830763548678291466/1178422329425002627/1198462332486045716)

**Comment by xHyperElectric** [comment] 2024-01-22 23:15
> enviroment:
> 
> * PORT=8211
> * PLAYERS=6
> * MULTITHREADING=FALSE
> * PUID=568
> * PGID=568

You likely need `UPDATE_ON_BOOT=true`

**Comment by thijsvanloef** [comment] 2024-01-26 09:19
@Lagicrus Do you still require help? Otherwise I will close the issue.

**Closed** 2024-01-31 15:00 UTC
Labels: help wanted, OS compatibility
