### ISSUE TITLE
Unofficial server fix. Wanted to put on your radar

### ISSUE THREAD

**Issue by jonlee-dev** [thijsvanloef/palworld-server-docker#121] opened 2024-01-26 01:52 UTC
**Is your feature request related to a problem? Please describe.**
Server performance is lacking. Likely my vCPUs are not doing the job

**Describe the solution you'd like**
Just wanted to put it on your radar

**Additional context**
https://github.com/VeroFess/PalWorld-Server-Unoffical-Fix

**Comment by NepPure** [comment] 2024-01-26 02:47
Good job !!!

Can test by set `- UPDATE_ON_BOOT=false`.

Replace `Pal/Binaries/Linux/PalServer-Linux-Test`.

**Comment by fryfrog** [comment] 2024-01-26 03:54
Duplicate of https://github.com/thijsvanloef/palworld-server-docker/issues/109.

**Comment by R4v3nl0** [comment] 2024-01-26 05:48
You can use it by yourself... It's because that binary has not been sure that not have malicious codes...
You know that many many servers using this docker image now, if this project uses that binary, it may makes many people incur financial or other losses.
Hope you can understand about that : )

**Comment by VeroFess** [comment] 2024-01-26 07:29
Oh I completely agree with this concern, so I thought maybe I could provide the byte positions that need to be modified and the data that needs to be modified to facilitate other script writers?

For 1.3.0 
```
1. C:\Users\VeroFess\Projects\PalPatch\1.13\PalServer-Linux-Test-Patch-Update-3-Beta: 189,756,648 bytes
2. C:\Users\VeroFess\Projects\PalPatch\1.13\PalServer-Linux-Test: 189,756,648 bytes

Offsets In Hex

69207B0:	48	55
69207B1:	31	41
69207B2:	C0	57
69207B3:	C3	41
69207B4:	90	56
6AD7F30:	48	55
6AD7F31:	31	41
6AD7F32:	C0	57
6AD7F33:	C3	41
6AD7F34:	90	56

```

**Comment by thijsvanloef** [comment] 2024-01-26 09:32
It is not only the security implication that make me think that this is a bad idea. 
For this to work with my docker container, I would have to automatically download the latest binary. 
That would create a huge dependency if the Palworld Devs decide to update their software not playing well with the unofficial patch resulting in a lot of servers breaking. Requiring me to constantly stay vigilant on when Palworld updates as well as when the unofficial patch updates. 

This is not something doable.

**Closed by thijsvanloef** 2024-01-26 09:32 UTC
