### ISSUE TITLE
Server is not showing up in community server list even when set to true.

### ISSUE THREAD

**Issue by gzukel** [thijsvanloef/palworld-server-docker#290] opened 2024-02-05 16:19 UTC
## Describe the bug

I am running both locally and in Kubernetes. I am a 10+ year devops engineer so I've doublechecked everything is set correctly. Even going in the container and checking. However, when I look at start.sh I see:

```
if [ "${COMMUNITY,,}" = true ]; then
    STARTCOMMAND+=("EpicApp=PalServer")
fi
```

I can see it being applied in logs:

`./PalServer.sh -port=8211 -queryport=27015 EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
`
However, when I goto Community Servers I don't see it show up in the list of servers. I don't see my server name in the list. I can join and play just fine via putting in the direct IP or load balancer DNS. Others can join as well. 

However, I don't see the server showing up in the community server list. 

## Container Logs
There aren't really any logs that indicate an issue:
```
*****EXECUTING USERMOD*****
usermod: no changes
*****STARTING INSTALL/UPDATE*****
tid(22) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...OK
"@sSteamCmdForcePlatformType" = "linux"
"@sSteamCmdForcePlatformBitness" = "64"

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 2.25 (50796336 / 2260207317)
 Update state (0x5) verifying install, progress: 27.81 (628599584 / 2260207317)
 Update state (0x5) verifying install, progress: 52.76 (1192522609 / 2260207317)
 Update state (0x5) verifying install, progress: 80.91 (1828658641 / 2260207317)
Success! App '2394010' fully installed.
*****CHECKING FOR EXISTING CONFIG*****
SERVER_NAME=5XEXP\/3XCAP\/NOPETSTAM\/5XITEM\/3XDROP\/ test server - coming soon on-demand customizable servers for rent
SERVER_DESCRIPTION=This is a test server for palworld-servers\.io\. Rentable reliable customizable servers coming soon\.
ADMIN_PASSWORD=REMOVED
PLAYERS=16
DIFFICULTY=None
DAYTIME_SPEEDRATE=1
NIGHTTIME_SPEEDRATE=1.5
EXP_RATE=5
PAL_CAPTURE_RATE=3
PAL_SPAWN_NUM_RATE=1.3
PAL_DAMAGE_RATE_ATTACK=1
PAL_DAMAGE_RATE_DEFENSE=1
PLAYER_DAMAGE_RATE_ATTACK=1
PLAYER_DAMAGE_RATE_DEFENSE=1
PLAYER_STOMACH_DECREASE_RATE=0.9
PLAYER_STAMINA_DECREASE_RATE=0.5
PLAYER_AUTO_HP_REGEN_RATE=1.5
PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP=3
PAL_STOMACH_DECREASE_RATE=0.5
PAL_STAMINA_DECREASE_RATE=0
PAL_AUTO_HP_REGEN_RATE=1
PAL_AUTO_HP_REGEN_RATE_IN_SLEEP=1
BUILD_OBJECT_DAMAGE_RATE=1
BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=1
COLLECTION_DROP_RATE=5
COLLECTION_OBJECT_HP_RATE=1
COLLECTION_OBJECT_RESPAWN_SPEED_RATE=5
ENEMY_DROP_ITEM_RATE=3
DEATH_PENALTY=All
ENABLE_PLAYER_TO_PLAYER_DAMAGE=true
ENABLE_FRIENDLY_FIRE=false
ENABLE_INVADER_ENEMY=true
ACTIVE_UNKO=false
ENABLE_AIM_ASSIST_PAD=true
ENABLE_AIM_ASSIST_KEYBOARD=false
DROP_ITEM_MAX_NUM=3000
DROP_ITEM_MAX_NUM_UNKO=100
BASE_CAMP_MAX_NUM=128
BASE_CAMP_WORKER_MAXNUM=30
DROP_ITEM_ALIVE_MAX_HOURS=1
AUTO_RESET_GUILD_NO_ONLINE_PLAYERS=false
AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS=128
GUILD_PLAYER_MAX_NUM=20
PAL_EGG_DEFAULT_HATCHING_TIME=1
WORK_SPEED_RATE=4
IS_MULTIPLAY=true
IS_PVP=true
CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP=true
ENABLE_NON_LOGIN_PENALTY=true
ENABLE_FAST_TRAVEL=true
IS_START_LOCATION_SELECT_BY_MAP=true
EXIST_PLAYER_AFTER_LOGOUT=true
ENABLE_DEFENSE_OTHER_GUILD_PLAYER=true
COOP_PLAYER_MAX_NUM=4
REGION=NA
USEAUTH=false
BAN_LIST_URL=https://api.palworldgame.com/api/banlist.txt
RCON_ENABLED=true
RCON_PORT=25575
BACKUP_ENABLED=true
*****STARTING SERVER*****
./PalServer.sh -port=8211 -queryport=27015 EpicApp=PalServer -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
time="2024-02-05T16:08:08Z" level=info msg="read crontab: /home/steam/server/crontab"
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
Shutdown handler: initalize.
Increasing per-process limit of core file size to infinity.
- Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
CAppInfoCacheReadFromDiskThread took 5 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
```

**Comment by win5923** [comment] 2024-02-05 17:16
Please check if your server is listed through the following website. Due to the community server search limit of only 200, occasionally not seeing your server is normal. 
> https://www.battlemetrics.com/servers/palworld

**Comment by thijsvanloef** [comment] 2024-02-05 18:27
Duplicate of https://github.com/thijsvanloef/palworld-server-docker/issues/78

**Closed by thijsvanloef** 2024-02-05 18:27 UTC
