### ISSUE TITLE
Latest Update Changes Name of Server

### ISSUE THREAD

**Issue by xHyperElectric** [thijsvanloef/palworld-server-docker#327] opened 2024-02-08 11:10 UTC
## Describe the bug

After I updated from 0.22.0 to 0.24.2 my server name changed to "." (a single period).

## To Reproduce

1. Set a server name like: "Palworld Server"
2. Try to log in 

## Expected behavior

Server name should be "Palworld Server"

## Actual behavior

Server name is "."

## Screenshots

![servername](https://github.com/thijsvanloef/palworld-server-docker/assets/71343435/adacd832-830f-4cb8-a723-5744a56746ad)
## OS information

- OS:  TrueNAS Scale via Docker
- Palworld Version:  1.4.0
- Docker Image Version:  0.24.2

## Additional context

My env variable is like so:

SERVER_NAME="Palworld Server"

**Comment by xHyperElectric** [comment] 2024-02-08 11:43
I actually think it may have no name.
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/71343435/48e449ce-fd80-4c0e-98e1-ee3ddcd89a2c)

![servername1](https://github.com/thijsvanloef/palworld-server-docker/assets/71343435/75352faa-b959-4c29-a54d-4fb6f9740994)

**Comment by rubyon** [comment] 2024-02-08 11:45
same problem

**Comment by terroreek** [comment] 2024-02-08 13:21
I can confirm the same, the server name name is now a "." and even though I have a password set for the server it is no longer asking for the server password.

**Comment by thijsvanloef** [comment] 2024-02-08 13:41
hi @xHyperElectric What happens when you remove the double quotes ("") around the name?

**Comment by xHyperElectric** [comment] 2024-02-08 13:54
> hi @xHyperElectric What happens when you remove the double quotes ("") around the name?

That seems to fix it which is interesting because I still have quotes around the server description and that functions fine.

**Comment by MSpreckels** [comment] 2024-02-08 13:59
Can you check how the actual ServerName setting looks like in PalworldSettings.ini on the container?

My guess is:
The script is already surrounding the settings with quotations and by you adding another quotation is basically reads as

ServerName=""Server name""

which results in

ServerName=""

Same as password

**Comment by thijsvanloef** [comment] 2024-02-08 14:00
@xHyperElectric Glad to hear, this is partially my bad, when I first created the server, I set the env variables to:
KEY="VALUE" however this is not supported by Docker and I've recently changed all the env's to:
KEY=VALUE

**Comment by xHyperElectric** [comment] 2024-02-08 14:02
> @xHyperElectric Glad to hear, this is partially my bad, when I first created the server, I set the env variables to:
> 
> `KEY="VALUE"` however this is not supported by Docker and I've recently changed all the env's to:
> 
> `KEY=VALUE`

I figured it was something like that but I didn't have time to troubleshoot yet. Does the server name env update the palworld settings.ini file now instead of being a launch command?

**Comment by thijsvanloef** [comment] 2024-02-08 14:07
@xHyperElectric Yes it does, only the following will be added to the launch command as there is no easy way of putting those in the settings.ini:
-port
-queryport
EpicApp=PalServer
-useperfthreads" "-NoAsyncLoadingThread" "-UseMultithreadForDS

**Comment by thijsvanloef** [comment] 2024-02-08 14:07
Feel free to close the issue, if it has been resolved :)

**Closed** 2024-02-08 14:21 UTC
Labels: bug
