### ISSUE TITLE
I couldn't backup in the shell script

### ISSUE THREAD

**Issue by ckbso19** [thijsvanloef/palworld-server-docker#254] opened 2024-02-01 18:03 UTC
## Describe the bug
exec palworld-server backup doesn't work in my shell script

## To Reproduce

I write a script to check available memory and restart docker container
anything is ok but the backup 
"exec palworld-server backup"doesn't work in my shell script

## Desktop (please complete the following information)

- OS: Ubuntu
- Version 23.04
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/105469076/c8deec3b-1855-40bf-905c-f8935c19a418)

**Comment by win5923** [comment] 2024-02-01 19:06
any error messenge?

**Comment by Dashboy1998** [comment] 2024-02-01 20:05
Does the restart work in your script?

If I had to guess sudo is prompting for a password.

**Comment by ckbso19** [comment] 2024-02-02 01:38
> Does the restart work in your script?
> 
> If I had to guess sudo is prompting for a password.

it works

**Comment by Dashboy1998** [comment] 2024-02-02 01:47
I am unable to reproduce the issue.

**Comment by thijsvanloef** [comment] 2024-02-02 08:46
@ckbso19 I am also unable to reproduce this issue, since this is also an external script I am not able to help you. 
If you want you can ask the community for help(https://discord.gg/GU2vkyHjkV), however I am marking this issue as wontfix.

**Closed by thijsvanloef** 2024-02-02 08:46 UTC
Labels: waiting for feedback
