### ISSUE TITLE
./PalServer.sh: No such file or directory

### ISSUE THREAD

**Issue by hengwuming** [thijsvanloef/palworld-server-docker#226] opened 2024-01-30 17:43 UTC
## Describe the bug
SERVER_NAME=World of Pals
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
SERVER_DESCRIPTION=Awesome World of Pal
## To Reproduce
docker run -d \
    --name palworld-server \
    -p 8211:8211/udp \
    -p 27015:27015/udp \
    -v /mnt/sata1-1/Configs/palworld:/palworld/ \
    -e PUID=1000 \
    -e PGID=1000 \
    -e PORT=8211 \
    -e PLAYERS=16 \
    -e MULTITHREADING=true \
    -e RCON_ENABLED=true \
    -e RCON_PORT=25575 \
    -e Asia/Shanghai \
    -e ADMIN_PASSWORD="adminPasswordHere" \
    -e SERVER_PASSWORD="worldofpals" \
    -e COMMUNITY=false \
    -e SERVER_NAME="World of Pals" \
    -e SERVER_DESCRIPTION="Awesome World of Pal" \
    --restart unless-stopped \
    thijsvanloef/palworld-server-docker:latest

## Desktop (please complete the following information)

- OS: istoreos 22.03.6 2024012613
- Browser chrome
## Container/Host Logs 
SERVER_NAME=World of Pals
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
SERVER_DESCRIPTION=Awesome World of Pal
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
SERVER_PASSWORD=worldofpals
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
ADMIN_PASSWORD=adminPasswordHere
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
PLAYERS=16
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
RCON_ENABLED=true
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
RCON_PORT=25575
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
BACKUP_ENABLED=true
*****STARTING SERVER*****
./PalServer.sh -port=8211 -queryport=27015 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
./start.sh: line 308: ./PalServer.sh: No such file or directory
time="2024-01-30T17:33:10Z" level=info msg="read crontab: /home/steam/server/crontab"
*****EXECUTING USERMOD*****
usermod: no changes
*****STARTING INSTALL/UPDATE*****
/home/steam/steamcmd/steamcmd.sh: line 38: /home/steam/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error
*****CHECKING FOR EXISTING CONFIG*****
*****GENERATING CONFIG*****
timeout: failed to run command './PalServer.sh': No such file or directory
cp: cannot stat '/palworld/DefaultPalWorldSettings.ini': No such file or directory
SERVER_NAME=World of Pals
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
SERVER_DESCRIPTION=Awesome World of Pal
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
SERVER_PASSWORD=worldofpals
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
ADMIN_PASSWORD=adminPasswordHere
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
PLAYERS=16
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
RCON_ENABLED=true
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
RCON_PORT=25575
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
BACKUP_ENABLED=true
*****STARTING SERVER*****
./PalServer.sh -port=8211 -queryport=27015 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
./start.sh: line 308: ./PalServer.sh: No such file or directory
time="2024-01-30T17:33:41Z" level=info msg="read crontab: /home/steam/server/crontab"
*****EXECUTING USERMOD*****
usermod: no changes
*****STARTING INSTALL/UPDATE*****
/home/steam/steamcmd/steamcmd.sh: line 38: /home/steam/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error
*****CHECKING FOR EXISTING CONFIG*****
*****GENERATING CONFIG*****
timeout: failed to run command './PalServer.sh': No such file or directory
cp: cannot stat '/palworld/DefaultPalWorldSettings.ini': No such file or directory
SERVER_NAME=World of Pals
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
SERVER_DESCRIPTION=Awesome World of Pal
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
SERVER_PASSWORD=worldofpals
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
ADMIN_PASSWORD=adminPasswordHere
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
PLAYERS=16
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
RCON_ENABLED=true
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
RCON_PORT=25575
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
BACKUP_ENABLED=true
*****STARTING SERVER*****
./PalServer.sh -port=8211 -queryport=27015 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
./start.sh: line 308: ./PalServer.sh: No such file or directory
time="2024-01-30T17:34:38Z" level=info msg="read crontab: /home/steam/server/crontab"
*****EXECUTING USERMOD*****
usermod: no changes
*****STARTING INSTALL/UPDATE*****
/home/steam/steamcmd/steamcmd.sh: line 38: /home/steam/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error
*****CHECKING FOR EXISTING CONFIG*****
*****GENERATING CONFIG*****
timeout: failed to run command './PalServer.sh': No such file or directory
cp: cannot stat '/palworld/DefaultPalWorldSettings.ini': No such file or directory
SERVER_NAME=World of Pals
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
SERVER_DESCRIPTION=Awesome World of Pal
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
SERVER_PASSWORD=worldofpals
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
ADMIN_PASSWORD=adminPasswordHere
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
PLAYERS=16
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
RCON_ENABLED=true
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
RCON_PORT=25575
sed: can't read /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini: No such file or directory
BACKUP_ENABLED=true
*****STARTING SERVER*****
./PalServer.sh -port=8211 -queryport=27015 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
./start.sh: line 308: ./PalServer.sh: No such file or directory
time="2024-01-30T17:35:44Z" level=info msg="read crontab: /home/steam/server/crontab"
## Additional context

my cpu is N5000
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/44749309/ae7f32b6-bd11-4291-904e-9c5ca94708ef)

**Comment by thijsvanloef** [comment] 2024-01-30 19:09
Duplicate of https://github.com/thijsvanloef/palworld-server-docker/issues/28

**Closed by thijsvanloef** 2024-01-30 19:09 UTC
