### ISSUE TITLE
Most recent PR merge is ignoring env vars

### ISSUE THREAD

**Issue by lrobles-iterable** [thijsvanloef/palworld-server-docker#212] opened 2024-01-29 21:56 UTC
## Describe the bug

After the most recent PR merge https://github.com/thijsvanloef/palworld-server-docker/pull/203/, settings in Palworldsettings.ini are being ignored.

Things such as server name, server password are not being set after removing them from the startup command

## To Reproduce

1. Pull latest container
2. set env vars for server name and password
3. they are ignored

## Expected behavior

EITHER options that were previously added to the startup line should be set, or allow us to set our own startup command options

## Screenshots

My env vars being set, but the server is named "Default palworld server" and no password is set
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/98352913/613c3e92-4759-42b4-acac-22bedc54e755)

## Desktop (please complete the following information)

- OS: [e.g. Windows 10, Ubuntu, Debian]

## docker-compose.yml contents

```yaml
      containers:
      - name: palworld
        image: thijsvanloef/palworld-server-docker:latest
        env:
        - name: PLAYERS
          value: "16"
        - name: "COMMUNITY"
          value: "true"
        - name: "ADMIN_PASSWORD"
          value: "xxxxx"
        - name: "SERVER_PASSWORD"
          value: "xxxxx"
        - name: "SERVER_NAME"
          value: "xxxxxx"
        - name: "RCON_PORT"
          value: "25575"
        - name: "RCON_ENABLED"
          value: "true"
        - name: "BACKUP_CRON_EXPRESSION"
```

**Comment by thijsvanloef** [comment] 2024-01-29 23:13
If you are able to please share the contents of your PalWorldSettings.ini.
Also are you using any special characters in your name/password?

**Comment by NobleKangaroo** [comment] 2024-01-29 23:42
> If you are able to please share the contents of your PalWorldSettings.ini. Also are you using any special characters in your name/password?

You've done an amazing job with this container but it's now not working for my friends and I. Unfortunately the configuration is not loading now due to #203 which was actually not necessary, as you could provide spaces in the server name if you didn't provide quotes. Example (using Docker Swarm) which was working before #203:

```
version: '3.9'

x-nfs-driver-opts:
  &nfs-driver-opts
  type: nfs
  o: addr=nfs-server.example.com,nolock,tcp,hard

volumes:
  palworld_server:
    driver_opts:
      <<: *nfs-driver-opts
      device: ':/mnt/palworld_server'

services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - PORT=8211
      - PLAYERS=20
      - COMMUNITY=true
      - SERVER_NAME=My Server Name Here
      - SERVER_DESCRIPTION=Pikachu, I choose you!
      - SERVER_PASSWORD=mypass
      - ADMIN_PASSWORD=theadminpass
      - MULTITHREADING=true
      - RCON_ENABLED=true
      - RCON_PORT=25575
      # Customizations
      - DAYTIME_SPEEDRATE=0.25
      - NIGHTTIME_SPEEDRATE=3.0
      - PAL_EGG_DEFAULT_HATCHING_TIME=3.6
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    volumes:
      - palworld_server:/palworld
    deploy:
      placement:
        constraints:
          - node.labels.function == worker
        preferences:
          - spread: node.labels.zone
```

Could you maybe revert the change and re-build on Docker Hub until this is sorted out? At least that way it would be back to its original mostly- working state.

Thanks again, sorry this happened, hope to be able to play tonight.

**Comment by thijsvanloef** [comment] 2024-01-30 06:19
Please make sure that the Env variable values are quoted in the docker compose

**Comment by thijsvanloef** [comment] 2024-01-30 08:04
@NobleKangaroo If you do not quote your names/discription the following happens:

```ini
ServerName="World of Pals",ServerDescription=Pikachu, I choose you!,AdminPassword="adminPasswordHere",
```
Which invalidates the PalWorldSettings.ini

**Comment by beomseok-park** [comment] 2024-01-30 08:36
See https://github.com/thijsvanloef/palworld-server-docker/pull/222

**Comment by Marc--** [comment] 2024-01-30 10:41
Hi there, i can confirm the problem on my server. env variables are not applied. It appends with 0.19 update.

I don't have specials characters in server name or password.

I revert to 0.18 and it's working.


Here is my Compose and PalWorldSettings.ini file if it can help.

`---
version: "3.0"
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld-server
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    network_mode: prod_bridge
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Paris
      - PUBLIC_IP=A.B.C.D
      - PORT=8211
      - QUERY_PORT=27015
      - RCON_PORT=25575
      - PLAYERS=4
      - MULTITHREADING=true
      - ENABLE_RCON=true
      - COMMUNITY=true
      - SERVER_PASSWORD="ASHORTERONE"
      - SERVER_NAME="![0 19](https://github.com/thijsvanloef/palworld-server-docker/assets/9568739/d2e07855-3519-4224-af23-1fa009aafb74)"
      - ADMIN_PASSWORD="AVERYLONGPASSWORD"
      - BACKUP_CRON_EXPRESSION=0 */2 * * *
      - DELETE_OLD_BACKUPS=true
      - OLD_BACKUP_DAYS=30
    volumes:
      - /srv/dev-disk-by-uuid-1da99476-7b55-497e-b2ba-7571787f2bab/docker/palworld:/palworld`




`[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None,DayTimeSpeedRate=1.000000,NightTimeSpeedRate=1.000000,ExpRate=1.000000,PalCaptureRate=1.000000,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=72.000000,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=4,ServerName=MYSERVERNAME,ServerDescription="",AdminPassword=AVERYLONGPASSWORD,ServerPassword=ASHORTERONE,PublicPort=8211,PublicIP="A.B.C.D",RCONEnabled=true,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")`

![0 18](https://github.com/thijsvanloef/palworld-server-docker/assets/9568739/96179e2f-d6e9-4721-bced-902fef3c6773)
![0 19](https://github.com/thijsvanloef/palworld-server-docker/assets/9568739/125c502e-e47d-49e2-ae23-890f17c43909)

**Comment by thijsvanloef** [comment] 2024-01-30 19:07
Problem should be resolved in update 0.19.1 thanks to `beomseok-park`, please pull the latest image and check if your issue has been resolved.

**Comment by PulsarFTW** [comment] 2024-01-30 20:09
I had the same issue on v0.19, I rolled back to v0.18 and it was working. I just tested updating to 0.19.1 and it's still setting default options.

**Comment by thijsvanloef** [comment] 2024-01-30 20:33
@PulsarFTW I've also change the docker-compose.yml example, could you try that with 0.19.1

**Comment by thijsvanloef** [comment] 2024-01-30 21:35
If you are still having trouble after updating, please remove your PalWorldSettings.ini and restart your container.

**Comment by gitgudchannel** [comment] 2024-01-30 22:31
I had changed the PAL_EGG_DEFAULT_HATCHING_TIME and some other env vars and now I restarted the container and the hatching time is infinite (99 hours +++) and the worktime multiplier is also infinite, can't craft anything anymore. I reverted the changes, tried 0.18, 0.19, 0.19.1 restarted the container, deleted the default settings .ini but nothing helped so far. Is the server backup bugged for good now?

**Comment by NobleKangaroo** [comment] 2024-01-31 04:55
> @NobleKangaroo If you do not quote your names/discription the following happens:
> 
> ```ini
> ServerName="World of Pals",ServerDescription=Pikachu, I choose you!,AdminPassword="adminPasswordHere",
> ```
> 
> Which invalidates the PalWorldSettings.ini

I don't know how but when NOT quoting the settings, the server is operating fine and the server name and description are good but when quoting them, the server name appears as the first word with a quote at the beginning. For instance if I set `SERVER_NAME="World of Pals"` and run it, the server name in-game shows as just `"World` and similarly if I set `SERVER_DESCRIPTION="Pikachu, I choose you!"` then the server description in-game just shows up as `"Pikachu` .... it's kind of like the rcon-cli issue where the spaces cause the arguments to get truncated after the first one.

As you mention, though, the PalWorldSettings.ini do look like this:
```
[/Script/Pal.PalGameWorldSettings]
OptionSettings=(Difficulty=None,DayTimeSpeedRate=0.25,NightTimeSpeedRate=3.0,ExpRate=1.0,PalCaptureRate=1.0,PalSpawnNumRate=1.000000,PalDamageRateAttack=1.000000,PalDamageRateDefense=1.000000,PlayerDamageRateAttack=1.000000,PlayerDamageRateDefense=1.000000,PlayerStomachDecreaceRate=1.000000,PlayerStaminaDecreaceRate=1.000000,PlayerAutoHPRegeneRate=1.000000,PlayerAutoHpRegeneRateInSleep=1.000000,PalStomachDecreaceRate=1.000000,PalStaminaDecreaceRate=1.000000,PalAutoHPRegeneRate=1.000000,PalAutoHpRegeneRateInSleep=1.000000,BuildObjectDamageRate=1.000000,BuildObjectDeteriorationDamageRate=1.000000,CollectionDropRate=1.000000,CollectionObjectHpRate=1.000000,CollectionObjectRespawnSpeedRate=1.000000,EnemyDropItemRate=1.000000,DeathPenalty=All,bEnablePlayerToPlayerDamage=False,bEnableFriendlyFire=False,bEnableInvaderEnemy=True,bActiveUNKO=False,bEnableAimAssistPad=True,bEnableAimAssistKeyboard=False,DropItemMaxNum=3000,DropItemMaxNum_UNKO=100,BaseCampMaxNum=128,BaseCampWorkerMaxNum=15,DropItemAliveMaxHours=1.000000,bAutoResetGuildNoOnlinePlayers=False,AutoResetGuildTimeNoOnlinePlayers=72.000000,GuildPlayerMaxNum=20,PalEggDefaultHatchingTime=3.6,WorkSpeedRate=1.000000,bIsMultiplay=False,bIsPvP=False,bCanPickupOtherGuildDeathPenaltyDrop=False,bEnableNonLoginPenalty=True,bEnableFastTravel=True,bIsStartLocationSelectByMap=True,bExistPlayerAfterLogout=False,bEnableDefenseOtherGuildPlayer=False,CoopPlayerMaxNum=4,ServerPlayerMaxNum=20,ServerName=My Palworld Server,ServerDescription=Pikachu, I choose you!,AdminPassword=adminpassword,ServerPassword=somepassword,PublicPort=8211,PublicIP="",RCONEnabled=true,RCONPort=25575,Region="",bUseAuth=True,BanListURL="https://api.palworldgame.com/api/banlist.txt")
```

Specifically of note is the bit

ServerPlayerMaxNum=20,**`ServerName=My Palworld Server,ServerDescription=Pikachu, I choose you!`**,AdminPassword=

HOWEVER that's still working and the name and description in-game are displaying as intended as well as the password is working and the player count is working. I don't know if there's some case where having a space would invalidate the ini but at least in my case, it appears that's not the case at all.

**Comment by thijsvanloef** [comment] 2024-01-31 07:43
@NobleKangaroo are you sure you are on the latest image? The bug you are describing "only the first word with a quote" sounds like 0.18.0

**Comment by thijsvanloef** [comment] 2024-01-31 07:44
@lrobles-iterable are you still experiencing this issue with 0.19.1?

**Comment by thijsvanloef** [comment] 2024-01-31 08:05
Closing this issue to merge all related issues into one: https://github.com/thijsvanloef/palworld-server-docker/issues/239

**Closed by thijsvanloef** 2024-01-31 08:05 UTC

**Comment by NobleKangaroo** [comment] 2024-01-31 16:34
> @NobleKangaroo are you sure you are on the latest image? The bug you are describing "only the first word with a quote" sounds like 0.18.0

Yes this was on 0.18.0. Thanks for confirming that. I'll give `:latest` a spin again. Good work!
