### ISSUE TITLE
Why does the steam API get an error? 

### ISSUE THREAD

**Issue by duojiuhuitoui** [thijsvanloef/palworld-server-docker#50] opened 2024-01-22 12:58 UTC
*****STARTING SERVER*****
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
Shutdown handler: initalize.
Increasing per-process limit of core file size to infinity.
- Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
CAppInfoCacheReadFromDiskThread took 11 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.

docker-compose.yml 

version: '3.1'
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:latest
      restart: unless-stopped
      container_name: palworld-server
      ports:
        - 8211:8211/udp
        - 27015:27015/udp
      environment:
         - PUID=1000
         - PGID=1000
         - PORT=8211
         - PLAYERS=4
         - MULTITHREADING=true
         - COMMUNITY=true
         - SERVER_PASSWORD="pwd"
         - SERVER_NAME="lg-test"
         - ADMIN_PASSWORD="pwd"
      volumes:
         - ./palworld:/palworld/
   restarter:
      image: docker:cli
      volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
      command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart palworld; done"]
      restart: unless-stopped

**Comment by thijsvanloef** [comment] 2024-01-22 18:36
Duplicate of https://github.com/thijsvanloef/palworld-server-docker/issues/7

**Closed by thijsvanloef** 2024-01-22 18:36 UTC
Labels: not a bug

**Comment by duojiuhuitoui** [comment] 2024-01-23 00:55
Thank you for helping me.
