### ISSUE TITLE
Server not appearing in community server list

### ISSUE THREAD

**Issue by Laynezilla** [thijsvanloef/palworld-server-docker#78] opened 2024-01-24 00:28 UTC
## Describe the bug

Server not appearing on community server list after setup.

## To Reproduce

 - forward ports 8211 and 27015 in router
 - create directory and user
```shell
sudo mkdir -p /opt/docker/palworld/palworld/
sudo adduser --system --group --no-create-home --home /opt/docker/palworld/ palworld
```
 - add `/opt/docker/palworld/palworld.yaml` and `/opt/docker/palworld/palworld.env` files
 - set ownership and permissions
```shell
sudo chown -R palworld:palworld /opt/docker/palworld/
sudo chmod -R 755 /opt/docker/palworld/
```
 - run container
```shell
docker compose --file /opt/docker/palworld/palworld.yaml up -d
```

## Expected behavior

I should be able to go into game and find my server on the list of community servers.

## Desktop (please complete the following information):

- Kernel: Linux 5.4.203 x86_64 GNU/Linux
- OS: Debian 10

## docker-compose.yml contents

```yaml
services:
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: palworld
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    env_file:
      - /opt/docker/palworld/palworld.env
    volumes:
      - /opt/docker/palworld/palworld/:/palworld/
```

## docker .env file contents

```env
PUID=${id -u palworld}
PGID=${id -g palworld}
PORT=8211
PLAYERS=31
MULTITHREADING=false
RCON_ENABLED=true
RCON_PORT=25575
ADMIN_PASSWORD="multi-word-password"
COMMUNITY=true
SERVER_PASSWORD="password"
SERVER_NAME="Server name"
PUBLIC_IP=<external ip address>
PUBLIC_PORT=8211
QUERY_PORT=27015
```

## Container/Host Logs
Output for `docker logs palworld`:
```shell
*****EXECUTING USERMOD*****
*****STARTING INSTALL/UPDATE*****
tid(27) burning pthread_key_t == 0 so we never use it
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 0.49 (23068672 / 4729437191)
 Update state (0x61) downloading, progress: 1.32 (62330672 / 4729437191)
 Update state (0x61) downloading, progress: 1.63 (76929186 / 4729437191)
 Update state (0x61) downloading, progress: 3.22 (152426658 / 4729437191)
 Update state (0x61) downloading, progress: 4.91 (232118719 / 4729437191)
 Update state (0x61) downloading, progress: 7.62 (360301169 / 4729437191)
 Update state (0x61) downloading, progress: 12.22 (577771859 / 4729437191)
 Update state (0x61) downloading, progress: 17.18 (812455845 / 4729437191)
 Update state (0x61) downloading, progress: 23.41 (1107107630 / 4729437191)
 Update state (0x61) downloading, progress: 26.27 (1242373934 / 4729437191)
 Update state (0x61) downloading, progress: 30.13 (1425008904 / 4729437191)
 Update state (0x61) downloading, progress: 35.14 (1661776343 / 4729437191)
 Update state (0x61) downloading, progress: 39.79 (1881847492 / 4729437191)
 Update state (0x61) downloading, progress: 43.22 (2044183914 / 4729437191)
 Update state (0x61) downloading, progress: 46.06 (2178238336 / 4729437191)
 Update state (0x61) downloading, progress: 48.47 (2292288436 / 4729437191)
 Update state (0x61) downloading, progress: 51.79 (2449239029 / 4729437191)
 Update state (0x61) downloading, progress: 57.98 (2742253689 / 4729437191)
 Update state (0x61) downloading, progress: 63.32 (2994755793 / 4729437191)
 Update state (0x61) downloading, progress: 66.30 (3135499360 / 4729437191)
 Update state (0x61) downloading, progress: 68.35 (3232591375 / 4729437191)
 Update state (0x61) downloading, progress: 69.44 (3284049068 / 4729437191)
 Update state (0x61) downloading, progress: 70.66 (3341892300 / 4729437191)
 Update state (0x61) downloading, progress: 71.69 (3390499189 / 4729437191)
 Update state (0x61) downloading, progress: 72.77 (3441581896 / 4729437191)
 Update state (0x61) downloading, progress: 73.92 (3495845822 / 4729437191)
 Update state (0x61) downloading, progress: 74.87 (3540948031 / 4729437191)
 Update state (0x61) downloading, progress: 75.94 (3591618890 / 4729437191)
 Update state (0x61) downloading, progress: 77.02 (3642472421 / 4729437191)
 Update state (0x61) downloading, progress: 78.15 (3696216377 / 4729437191)
 Update state (0x61) downloading, progress: 79.13 (3742556959 / 4729437191)
 Update state (0x61) downloading, progress: 80.24 (3794973528 / 4729437191)
 Update state (0x61) downloading, progress: 81.36 (3847664764 / 4729437191)
 Update state (0x61) downloading, progress: 82.42 (3898064912 / 4729437191)
 Update state (0x61) downloading, progress: 83.57 (3952437321 / 4729437191)
 Update state (0x61) downloading, progress: 84.65 (4003312862 / 4729437191)
 Update state (0x61) downloading, progress: 85.81 (4058179099 / 4729437191)
 Update state (0x61) downloading, progress: 86.96 (4112828441 / 4729437191)
 Update state (0x61) downloading, progress: 88.09 (4166302328 / 4729437191)
 Update state (0x61) downloading, progress: 89.18 (4217823172 / 4729437191)
 Update state (0x61) downloading, progress: 90.32 (4271556444 / 4729437191)
 Update state (0x61) downloading, progress: 91.35 (4320482316 / 4729437191)
 Update state (0x61) downloading, progress: 92.71 (4384771606 / 4729437191)
 Update state (0x61) downloading, progress: 93.81 (4436887591 / 4729437191)
 Update state (0x61) downloading, progress: 95.06 (4495870601 / 4729437191)
 Update state (0x61) downloading, progress: 96.28 (4553362098 / 4729437191)
 Update state (0x61) downloading, progress: 97.49 (4610626051 / 4729437191)
 Update state (0x61) downloading, progress: 98.56 (4661330382 / 4729437191)
 Update state (0x61) downloading, progress: 99.93 (4726342110 / 4729437191)
 Update state (0x81) verifying update, progress: 2.57 (121678087 / 4729437191)
 Update state (0x81) verifying update, progress: 7.18 (339781895 / 4729437191)
 Update state (0x81) verifying update, progress: 13.44 (635487038 / 4729437191)
 Update state (0x81) verifying update, progress: 21.68 (1025557310 / 4729437191)
 Update state (0x81) verifying update, progress: 28.91 (1367407147 / 4729437191)
 Update state (0x81) verifying update, progress: 35.06 (1658161510 / 4729437191)
 Update state (0x81) verifying update, progress: 42.21 (1996262823 / 4729437191)
 Update state (0x81) verifying update, progress: 50.13 (2370849785 / 4729437191)
 Update state (0x81) verifying update, progress: 58.62 (2772437417 / 4729437191)
 Update state (0x81) verifying update, progress: 65.34 (3090108787 / 4729437191)
 Update state (0x81) verifying update, progress: 72.09 (3409315277 / 4729437191)
 Update state (0x81) verifying update, progress: 80.15 (3790469217 / 4729437191)
 Update state (0x81) verifying update, progress: 85.70 (4053026241 / 4729437191)
 Update state (0x81) verifying update, progress: 92.85 (4391229127 / 4729437191)
 Update state (0x81) verifying update, progress: 99.24 (4693413797 / 4729437191)
Success! App '2394010' fully installed.
*****CHECKING FOR EXISTING CONFIG*****
*****GENERATING CONFIG*****
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 8 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
RCON_ENABLED=true
RCON_PORT=25575
*****STARTING SERVER*****
./PalServer.sh -port=8211 -players=31 EpicApp=PalServer -publicip=<external ip address> -publicport=8211 -servername=Server name -serverpassword=password -adminpassword=multi-word-password -queryport=27015
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
Shutdown handler: initalize.
Increasing per-process limit of core file size to infinity.
- Existing per-process limit (soft=18446744073709551615, hard=18446744073709551615) is enough for us (need only 18446744073709551615)
CAppInfoCacheReadFromDiskThread took 3 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
```
Contents of `/home/steam/Steam/logs/stderr.txt`
```shell
01/24 00:05:21 Init: Installing breakpad exception handler for appid(steam)/version(1705108307)/tid(27)
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Steam Service Error: Failed to get Steam Service Start function
Shutting down: stopping app stats write job
```
Output of rcon-cli `Info` command:
```shell
Weird. This response is for another request.
Welcome to Pal Server[v0.1.2.0] Server
```

## Additional context

I feel like there is something I must be missing but I just can't figure out what's going on. But I'm not finding any information on any of the log outputs that would fix my issue. Sorry if I'm just missing something simple, it just feels like I'm not doing anything special with the container and it should be working.

**Comment by wkelton** [comment] 2024-01-24 02:05
I am seeing the exact same thing.

**Comment by fabifont** [comment] 2024-01-24 02:36
I can see my server here (https://www.battlemetrics.com/servers/palworld) but I can't find it with the search bar in the game. I think it's not our fault.

**Comment by Laynezilla** [comment] 2024-01-24 03:14
I do see my server listed there. Using the site's direct connect method for servers with passwords works as well. But that probably won't work for all of my users. Maybe it is just a Palworld issue?

I don't know if it relates, but when I try to add my server in steam > view > game server > favorites, it just says:
> Failure
> Did not find any servers at that address

Not sure what the normal behavior of Palworld servers are, if they can be added there or not like typical servers.

Sidenote, my server name is just the first word of what I set in the environment variables. If I double quote `"'Server name'"` it works. But that might be a different bug report.

**Comment by thijsvanloef** [comment] 2024-01-24 08:12
Duplicate of https://github.com/thijsvanloef/palworld-server-docker/issues/24

This is a known issue, which I am not able to fix, you can only search the first 200 servers in the server list in the game. This is something that needs to be addressed by the Palworld Devs

**Comment by thijsvanloef** [comment] 2024-01-24 08:32
Has also been mentioned in this discussion: https://github.com/thijsvanloef/palworld-server-docker/discussions/59

**Closed** 2024-01-24 13:32 UTC
Labels: not a bug
