### ISSUE TITLE
When response has chinese  is not working for rcon-cli return

### ISSUE THREAD

**Issue by yaoyaochil** [thijsvanloef/palworld-server-docker#297] opened 2024-02-06 07:56 UTC
<img width="543" alt="image" src="https://github.com/thijsvanloef/palworld-server-docker/assets/49603204/1d6bc477-f985-494d-a62d-c21eecc86e45">
<img width="609" alt="image" src="https://github.com/thijsvanloef/palworld-server-docker/assets/49603204/48f9f33d-6d0a-417d-a1f2-8375faf947d9">

not has chinese img:

<img width="486" alt="image" src="https://github.com/thijsvanloef/palworld-server-docker/assets/49603204/261a05eb-1249-4d38-a654-b1eed97fd2a9">

**Comment by thijsvanloef** [comment] 2024-02-06 11:21
Duplicate of https://github.com/thijsvanloef/palworld-server-docker/issues/253
This is not something I can fix

**Closed by thijsvanloef** 2024-02-06 11:21 UTC
