### ISSUE TITLE
ARM64 Exec format error

### ISSUE THREAD

**Issue by tinducvo** [thijsvanloef/palworld-server-docker#579] opened 2024-07-10 19:29 UTC
Using 0.38.1/0.38.2, I get the following on Oracle Cloud ARM64:
./PalServer-arm64.sh -port=8211 -queryport=27015 -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
time="2024-07-10T19:17:15Z" level=info msg="read crontab: /home/steam/server/crontab"
The file has been successfully copied: /palworld/linux64/steamclient.so -> /palworld/Pal/Binaries/Linux/steamclient.so
./PalServer-arm64.sh: 21: /palworld/Pal/Binaries/Linux/PalServer-Linux-Shipping: Exec format error

I also noticed the README references ARM64_DEVICE added in 0.39.0, which is unreleased.

---

The container works fine if I downgrade to 0.38.0.

**Comment by sonroyaalmerol** [comment] 2024-07-11 02:01
Hi! Please follow the issue template as much as possible next time. We'll need **OS, Hardware information** (see the details needed from the template) and **docker-compose.yml contents** (don't forget to remove secrets).

There has been no significant changes at all from 0.38.0 to 0.38.1 that would affect ARM64. It's all config/documentation additions only based from the diff: https://github.com/thijsvanloef/palworld-server-docker/compare/0.38.0...0.38.1

Most of the ARM64 changes are between 0.38.1 and 0.38.2 so that doesn't seem right. I believe our unit tests and builds for ARM64 are also executed on an Oracle Cloud ARM64 instance as well so there must be something else on your setup.

Also, vars labeled for 0.39.0 was released on 0.38.2, just a typo. We'll fix it soon. Thanks for letting us know!

**Comment by tinducvo** [comment] 2024-07-11 19:37
## Describe the bug

With the following configuration, I can start fresh with 0.38.0 then update to 0.38.2.

However, with my save data, when I try to upgrade to 0.38.1/0.38.2 or manually copy my palworld/Pal/Saved folder to the working docker container, I get the following:

```
/usr/local/bin/box64: line 32:    92 Segmentation fault      (core dumped) "$BINARY_PATH" "$@"
```

## OS information (IMPORTANT)

- OS: Ubuntu 22.04.4 LTS
- Kernel: 6.5.0-1025-oracle
- Palworld Version: v0.3.3.55731
- Docker Image Version: 27.0.3, build 7d4bcd8

## Hardware information (IMPORTANT)

- CPU: AMPERE ALTRA Q80-30 w/ 4 OCPUs 
- Memory: 24GB DDR4

## docker-compose.yml contents (IMPORTANT)

<details><summary>docker-compose.yml</summary>

```yaml
services:
   palworld:
      image: thijsvanloef/palworld-server-docker:v0.38.2
      restart: unless-stopped
      ports:
        - 8211:8211/udp # Game
        - 27015:27015/udp # Query
        - 8212:8212/tcp # REST API
        - 25575:25575/tcp # RCON
      environment:
         - ARM_COMPATIBILITY_MODE=true
         - PUID=1001
         - PGID=1001
         - PLAYERS=8
         - SERVER_PASSWORD=testing
         - MULTITHREADING=true
         - RCON_ENABLED=true
         - REST_API_ENABLED=true
         - ADMIN_PASSWORD=moretesting
         - COMMUNITY=true
         - SERVER_NAME=TestPals
         - SERVER_DESCRIPTION=We love testing.
         - REGION=NA
         - UPDATE_ON_BOOT=true
         - PAL_EGG_DEFAULT_HATCHING_TIME=36.000000
         - ENABLE_NON_LOGIN_PENALTY=false
         - DISABLE_GENERATE_ENGINE=false
         - LAN_SERVER_MAX_TICK_RATE=60
         - NET_SERVER_MAX_TICK_RATE=60
         - CONFIGURED_INTERNET_SPEED=104857600
         - CONFIGURED_LAN_SPEED=104857600
         - MAX_CLIENT_RATE=104857600
         - MAX_INTERNET_CLIENT_RATE=104857600
         - SMOOTH_FRAME_RATE=true
         - SMOOTH_FRAME_RATE_LOWER_LIMIT=30.000000
         - SMOOTH_FRAME_RATE_UPPER_LIMIT=60.000000
         - USE_FIXED_FRAME_RATE=false
         - FIXED_FRAME_RATE=60.000000
         - MIN_DESIRED_FRAME_RATE=30.000000
         - NET_CLIENT_TICKS_PER_SECOND=60
      volumes:
         - ./palworld:/palworld/
```
</details>

**Comment by sonroyaalmerol** [comment] 2024-07-11 20:31
This doesn't seem like the exec error you initially reported.

Segmentation faults are different and could be caused by a number of things. It seems to be more frequent on larger saves. The 0.38.2 update was aimed to minimize those segfaults.

While using the 0.38.2 image, try and set `ARM64_DEVICE` to `adlink`. See if that helps. 

This might be a duplicate of #571.

Also, `ARM_COMPATIBILITY_MODE` has been removed since 0.38.2 in favor of `USE_DEPOT_DOWNLOADER`. Both should be unnecessary for your setup.

**Comment by tinducvo** [comment] 2024-07-11 21:29
After adding the ARM64_DEVICE environment variable, I still get the following from docker logs:
```
BACKUP_ENABLED=true
Adding cronjob for auto backups
Cronjobs started
****Starting Server****
./PalServer-arm64.sh -queryport=27015 -publiclobby -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
time="2024-07-11T21:15:19Z" level=info msg="read crontab: /home/steam/server/crontab"
The file already exists: /palworld/Pal/Binaries/Linux/steamclient.so
Waiting for REST API(8212) port to open to show player logging...
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
Shutdown handler: initalize.
5.1.1-0+++UE5+Release-5.1 1008 0
Disabling core dumps.
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
Waiting for REST API(8212) port to open to show player logging...
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Game version is v0.3.3.55731
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
REST API started on port 8212
Waiting for REST API(8212) port to open to show player logging...
/usr/local/bin/box64: line 32:    92 Segmentation fault      (core dumped) "$BINARY_PATH" "$@"
```

It seems to segmentation fault before becoming joinable.

**Comment by sonroyaalmerol** [comment] 2024-07-11 22:29
Weird. These logs don't look like the logs I'm expecting from 0.38.2. I was expecting more verbosity as I've set it by default on 0.38.2.

Can you set `BOX64_ROLLING_LOG=1` and `BOX64_SHOWSEGV=1` then post the logs again?

**Comment by tinducvo** [comment] 2024-07-11 22:50
I saw more verbose logging, but sometimes it's just that segmentation fault. These runs are with the same configuration:

```
****EXECUTING USERMOD****
usermod: no changes
****Checking for new Palworld Server updates****
Current Version: 8939748203712584968
The server is up to date!
****Checking for available container updates****
The container is up to date!
****GENERATING CONFIG****
Using Env vars to create PalWorldSettings.ini
****Compiling PalWorldSettings.ini****
Compiling PalWorldSettings.ini done!
****Compiling Engine.ini****
Compiling Engine.ini done!
****GENERATING CRONTAB****
BACKUP_ENABLED=true
Adding cronjob for auto backups
Cronjobs started
****Starting Server****
./PalServer-arm64.sh -queryport=27015 -publiclobby -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
time="2024-07-11T22:40:21Z" level=info msg="read crontab: /home/steam/server/crontab"
The file already exists: /palworld/Pal/Binaries/Linux/steamclient.so
Waiting for REST API(8212) port to open to show player logging...
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
Shutdown handler: initalize.
5.1.1-0+++UE5+Release-5.1 1008 0
Disabling core dumps.
CAppInfoCacheReadFromDiskThread took 2 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
Waiting for REST API(8212) port to open to show player logging...
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Game version is v0.3.3.55731
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
REST API started on port 8212
Waiting for REST API(8212) port to open to show player logging...
/usr/local/bin/box64: line 32:    86 Segmentation fault      (core dumped) "$BINARY_PATH" "$@"
```
```
****EXECUTING USERMOD****
usermod: no changes
****Checking for new Palworld Server updates****
Current Version: 8939748203712584968
The server is up to date!
****Checking for available container updates****
The container is up to date!
****GENERATING CONFIG****
Using Env vars to create PalWorldSettings.ini
****Compiling PalWorldSettings.ini****
Compiling PalWorldSettings.ini done!
****Compiling Engine.ini****
Compiling Engine.ini done!
****GENERATING CRONTAB****
BACKUP_ENABLED=true
Adding cronjob for auto backups
Cronjobs started
****Starting Server****
./PalServer-arm64.sh -queryport=27015 -publiclobby -useperfthreads -NoAsyncLoadingThread -UseMultithreadForDS
time="2024-07-11T22:43:28Z" level=info msg="read crontab: /home/steam/server/crontab"
The file already exists: /palworld/Pal/Binaries/Linux/steamclient.so
Waiting for REST API(8212) port to open to show player logging...
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
Shutdown handler: initalize.
5.1.1-0+++UE5+Release-5.1 1008 0
Disabling core dumps.
CAppInfoCacheReadFromDiskThread took 2 milliseconds to initialize
Setting breakpad minidump AppID = 2394010
[S_API FAIL] Tried to access Steam interface SteamUser021 before SteamAPI_Init succeeded.
[S_API FAIL] Tried to access Steam interface SteamFriends017 before SteamAPI_Init succeeded.
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
[S_API FAIL] Tried to access Steam interface STEAMAPPS_INTERFACE_VERSION008 before SteamAPI_Init succeeded.
Waiting for REST API(8212) port to open to show player logging...
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils004 before SteamAPI_Init succeeded.
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Game version is v0.3.3.55731
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
Waiting for REST API(8212) port to open to show player logging...
REST API started on port 8212
Waiting for REST API(8212) port to open to show player logging...
LogPakFile: Display: Found Pak file ../../../Engine/Programs/CrashReportClient/Content/Paks/CrashReportClient.pak attempting to mount.
LogPakFile: Display: Mounting pak file ../../../Engine/Programs/CrashReportClient/Content/Paks/CrashReportClient.pak.
LogPakFile: Display: Mounted Pak file '../../../Engine/Programs/CrashReportClient/Content/Paks/CrashReportClient.pak', mount point: '../../../Engine/'
LogICUInternationalization: ICU TimeZone Detection - Raw Offset: +0:00, Platform Override: ''
LogInit: Build: ++UE5+Release-5.1-CL-0
LogInit: Engine Version: 5.1.1-0+++UE5+Release-5.1
LogInit: Compatible Engine Version: 5.1.0-0+++UE5+Release-5.1
LogInit: Net CL: 0
LogInit: OS: Debian GNU/Linux 12 (bookworm) (6.5.0-1025-oracle), CPU: Box64 on Neoverse-N1 @1000 MHz, GPU: UnknownVendor PCI-id: 1af4-1050 (108e-1100)
LogInit: Compiled (64-bit): Jun 12 2024 15:50:14
LogInit: Compiled with Clang: 13.0.1 (https://github.com/llvm/llvm-project 75e33f71c2dae584b13a7d1186ae0a038ba98838)
LogInit: Build Configuration: Shipping
LogInit: Branch Name: ++UE5+Release-5.1
LogInit: Command Line:  -Abslog="/palworld/Pal/Saved/Logs/Pal-CRC.log" -Unattended -ImplicitSend "/palworld/Pal/Saved/Crashes/crashinfo-Pal-pid-86-1CF7AA1D7AE244DC88D17BC6381883AC/" -unattended
LogInit: Base Directory: /palworld/Engine/Binaries/Linux/
LogInit: Allocator: Mimalloc
LogInit: Installed Engine Build: 1
LogInit: Presizing for max 100000 objects, including 0 objects not considered by GC, pre-allocating 0 bytes for permanent pool.
LogInit: Object subsystem initialized
LogConfig: Applying CVar settings from Section [ConsoleVariables] File [Engine]
[2024.07.11-22.46.35:692][  0]LogInit: Unix hardware info:
[2024.07.11-22.46.35:692][  0]LogInit:  - we are the first instance of this executable
[2024.07.11-22.46.35:692][  0]LogInit:  - this process' id (pid) is 246, parent process' id (ppid) is 86
[2024.07.11-22.46.35:692][  0]LogInit:  - we are not running under debugger
[2024.07.11-22.46.35:692][  0]LogInit:  - machine network name is 'a5a2d3704c5f'
[2024.07.11-22.46.35:693][  0]LogInit:  - user name is 'steam' (steam)
[2024.07.11-22.46.35:693][  0]LogInit:  - we're logged in locally
[2024.07.11-22.46.35:693][  0]LogInit:  - we're running with rendering
[2024.07.11-22.46.35:693][  0]LogInit:  - CPU: GenuineIntel 'Box64 on Neoverse-N1 @1000 MHz' (signature: 0x40661)
[2024.07.11-22.46.35:693][  0]LogInit:  - Number of physical cores available for the process: 4
[2024.07.11-22.46.35:693][  0]LogInit:  - Number of logical cores available for the process: 4
[2024.07.11-22.46.35:694][  0]LogInit:  - Cache line size: 64
[2024.07.11-22.46.35:694][  0]LogInit:  - GPU Brand Info: UnknownVendor PCI-id: 1af4-1050 (108e-1100)
[2024.07.11-22.46.35:694][  0]LogInit:  - Memory allocator used: Mimalloc
[2024.07.11-22.46.35:694][  0]LogInit:  - This binary is optimized with LTO: no, PGO: no, instrumented for PGO data collection: no
[2024.07.11-22.46.35:694][  0]LogInit:  - This is an internal build.
[2024.07.11-22.46.35:695][  0]LogCore: Skipped benchmarking clocks because the engine is running in a standalone program mode - CLOCK_MONOTONIC will be used.
[2024.07.11-22.46.35:695][  0]LogInit: Unix-specific commandline switches:
[2024.07.11-22.46.35:695][  0]LogInit:  -ansimalloc - use malloc()/free() from libc (useful for tools like valgrind and electric fence)
[2024.07.11-22.46.35:695][  0]LogInit:  -jemalloc - use jemalloc for all memory allocation
[2024.07.11-22.46.35:695][  0]LogInit:  -binnedmalloc - use binned malloc  for all memory allocation
[2024.07.11-22.46.35:695][  0]LogInit:  -filemapcachesize=NUMBER - set the size for case-sensitive file mapping cache
[2024.07.11-22.46.35:695][  0]LogInit:  -useksm - uses kernel same-page mapping (KSM) for mapped memory (OFF)
[2024.07.11-22.46.35:695][  0]LogInit:  -ksmmergeall - marks all mmap'd memory pages suitable for KSM (OFF)
[2024.07.11-22.46.35:695][  0]LogInit:  -preloadmodulesymbols - Loads the main module symbols file into memory (OFF)
[2024.07.11-22.46.35:695][  0]LogInit:  -sigdfl=SIGNAL - Allows a specific signal to be set to its default handler rather then ignoring the signal
[2024.07.11-22.46.35:695][  0]LogInit:  -crashhandlerstacksize - Allows setting crash handler stack sizes (204800)
[2024.07.11-22.46.35:695][  0]LogInit:  -noexclusivelockonwrite - disables marking files created by the engine as exclusive locked while the engine has them opened
[2024.07.11-22.46.35:703][  0]LogInit:  -httpproxy=ADDRESS:PORT - redirects HTTP requests to a proxy (only supported if compiled with libcurl)
[2024.07.11-22.46.35:703][  0]LogInit:  -reuseconn - allow libcurl to reuse HTTP connections (only matters if compiled with libcurl)
[2024.07.11-22.46.35:703][  0]LogInit:  -virtmemkb=NUMBER - sets process virtual memory (address space) limit (overrides VirtualMemoryLimitInKB value from .ini)
[2024.07.11-22.46.35:703][  0]LogInit:  - Physical RAM available (not considering process quota): 24 GB (23981 MB, 24557404 KB, 25146781696 bytes)
[2024.07.11-22.46.35:703][  0]LogInit:  - VirtualMemoryAllocator pools will grow at scale 1.4
[2024.07.11-22.46.35:703][  0]LogInit:  - MemoryRangeDecommit() will be a no-op (re-run with -vmapoolevict to change)
[2024.07.11-22.46.35:703][  0]LogInit:  - PageSize 4096
[2024.07.11-22.46.35:703][  0]LogInit:  - BinnedPageSize 65536
[2024.07.11-22.46.35:822][  0]LogUObjectArray: 419 objects as part of root set at end of initial load.
[2024.07.11-22.46.35:822][  0]LogUObjectAllocator: 89056 out of 0 bytes used by permanent object pool.
[2024.07.11-22.46.35:823][  0]LogUObjectArray: CloseDisregardForGC: 0/0 objects in disregard for GC pool
[2024.07.11-22.46.35:828][  0]LogPaths: Warning: No paths for game localization data were specifed in the game configuration.
[2024.07.11-22.46.35:829][  0]LogInit: Using OS detected language (en-US-POSIX).
[2024.07.11-22.46.35:829][  0]LogInit: Using OS detected locale (en-US-POSIX).
[2024.07.11-22.46.35:830][  0]LogInit: Warning: No paths for engine localization data were specifed in the engine configuration.
[2024.07.11-22.46.35:835][  0]LogTextLocalizationManager: No localization for 'en-US-POSIX' exists, so 'en' will be used for the language.
[2024.07.11-22.46.35:836][  0]LogTextLocalizationManager: No localization for 'en-US-POSIX' exists, so 'en' will be used for the locale.
[2024.07.11-22.46.35:841][  0]LogInit: Using OS detected language (en-US-POSIX).
[2024.07.11-22.46.35:841][  0]LogInit: Using OS detected locale (en-US-POSIX).
[2024.07.11-22.46.35:841][  0]LogTextLocalizationManager: No localization for 'en-US-POSIX' exists, so 'en' will be used for the language.
[2024.07.11-22.46.35:841][  0]LogTextLocalizationManager: No localization for 'en-US-POSIX' exists, so 'en' will be used for the locale.
[2024.07.11-22.46.35:858][  0]LogPackageLocalizationCache: Processed 2 localized package path(s) for 1 prioritized culture(s) in 0.005039 seconds
[2024.07.11-22.46.35:861][  0]CrashReportCoreLog: CrashReportClientVersion=1.0
[2024.07.11-22.46.35:861][  0]CrashReportCoreLog: CrashReportReceiver disabled
[2024.07.11-22.46.35:861][  0]CrashReportCoreLog: DataRouterUrl: https://o1291919.ingest.sentry.io/api/6513339/unreal/4a1a3921f51f4975b4cf8dd19022cb20/
[2024.07.11-22.46.35:891][  0]CrashReportCoreLog: Initial state = Unknown UploadState value
[2024.07.11-22.46.35:891][  0]CrashReportCoreLog: Initial state = Unknown UploadState value
[2024.07.11-22.46.35:903][  0]LogCrashDebugHelper: DepotName: //UE5/Release-5.1
[2024.07.11-22.46.35:903][  0]LogCrashDebugHelper: BuiltFromCL: 0
[2024.07.11-22.46.35:903][  0]LogCrashDebugHelper: EngineVersion: 5.1.1-0+++UE5+Release-5.1
[2024.07.11-22.46.35:903][  0]LogCrashDebugHelper: BuildVersion: ++UE5+Release-5.1-CL-0
[2024.07.11-22.46.36:891][  0]CrashReportCoreLog: Got 3 pending files to upload from 'crashinfo-Pal-pid-86-1CF7AA1D7AE244DC88D17BC6381883AC'
[2024.07.11-22.46.36:891][  0]CrashReportCoreLog: State change from Ready to SendingFiles
[2024.07.11-22.46.36:891][  0]CrashReportCoreLog: CompressAndSendData have 3 pending files
[2024.07.11-22.46.36:893][  0]CrashReportCoreLog: CompressAndSendData compressing 332 bytes ('/palworld/Pal/Saved/Crashes/crashinfo-Pal-pid-86-1CF7AA1D7AE244DC88D17BC6381883AC/Diagnostics.txt')
[2024.07.11-22.46.36:894][  0]CrashReportCoreLog: CompressAndSendData compressing 152 bytes ('/palworld/Pal/Saved/Crashes/crashinfo-Pal-pid-86-1CF7AA1D7AE244DC88D17BC6381883AC/CrashReportClient.ini')
[2024.07.11-22.46.36:894][  0]CrashReportCoreLog: CompressAndSendData compressing 4849 bytes ('/palworld/Pal/Saved/Crashes/crashinfo-Pal-pid-86-1CF7AA1D7AE244DC88D17BC6381883AC/CrashContext.runtime-xml')
[2024.07.11-22.46.37:159][  0]LogInit: Using libcurl 7.83.1
[2024.07.11-22.46.37:159][  0]LogInit:  - built for Linux
[2024.07.11-22.46.37:160][  0]LogInit:  - supports SSL with OpenSSL/1.1.1n
[2024.07.11-22.46.37:160][  0]LogInit:  - supports HTTP deflate (compression) using libz 1.2.12
[2024.07.11-22.46.37:160][  0]LogInit:  - other features:
[2024.07.11-22.46.37:160][  0]LogInit:      CURL_VERSION_SSL
[2024.07.11-22.46.37:160][  0]LogInit:      CURL_VERSION_LIBZ
[2024.07.11-22.46.37:160][  0]LogInit:      CURL_VERSION_IPV6
[2024.07.11-22.46.37:160][  0]LogInit:      CURL_VERSION_ASYNCHDNS
[2024.07.11-22.46.37:161][  0]LogInit:      CURL_VERSION_LARGEFILE
[2024.07.11-22.46.37:165][  0]LogInit:  CurlRequestOptions (configurable via config and command line):
[2024.07.11-22.46.37:165][  0]LogInit:  - bVerifyPeer = false  - Libcurl will NOT verify peer certificate
[2024.07.11-22.46.37:165][  0]LogInit:  - bUseHttpProxy = false  - Libcurl will NOT use HTTP proxy
[2024.07.11-22.46.37:165][  0]LogInit:  - bDontReuseConnections = false  - Libcurl will reuse connections
[2024.07.11-22.46.37:165][  0]LogInit:  - MaxHostConnections = 16  - Libcurl will limit the number of connections to a host
[2024.07.11-22.46.37:165][  0]LogInit:  - LocalHostAddr = Default
[2024.07.11-22.46.37:165][  0]LogInit:  - BufferSize = 65536
[2024.07.11-22.46.37:172][  0]CrashReportCoreLog: Sending HTTP request: https://o1291919.ingest.sentry.io/api/6513339/unreal/4a1a3921f51f4975b4cf8dd19022cb20/?AppID=CrashReporter&AppVersion=5.1.1-0%2B%2B%2BUE5%2BRelease-5.1&AppEnvironment=Release&UploadType=crashreports&UserID=-000003e9%7C%7C
[2024.07.11-22.46.37:447][  0]CrashReportCoreLog: OnProcessRequestComplete(), State=SendingFiles bSucceeded=1
[2024.07.11-22.46.37:447][  0]CrashReportCoreLog: State change from SendingFiles to SendingFiles
[2024.07.11-22.46.37:447][  0]CrashReportCoreLog: All uploads done
[2024.07.11-22.46.37:447][  0]CrashReportCoreLog: State change from SendingFiles to Finished
[2024.07.11-22.46.37:914][  0]CrashReportCoreLog: Final state (Receiver) = Finished
[2024.07.11-22.46.37:915][  0]CrashReportCoreLog: Final state (Receiver) = Unknown UploadState value
[2024.07.11-22.46.37:934][  0]LogCore: Engine exit requested (reason: CrashReportClientApp RequestExit)
[2024.07.11-22.46.37:934][  0]LogExit: Preparing to exit.
[2024.07.11-22.46.37:967][  0]LogExit: Object subsystem successfully closed.
[2024.07.11-22.46.37:970][  0]LogModuleManager: Shutting down and abandoning module HTTP (12)
[2024.07.11-22.46.38:007][  0]LogModuleManager: Shutting down and abandoning module SSL (11)
[2024.07.11-22.46.38:021][  0]LogModuleManager: Shutting down and abandoning module CrashDebugHelper (8)
[2024.07.11-22.46.38:022][  0]LogModuleManager: Shutting down and abandoning module CoreUObject (6)
[2024.07.11-22.46.38:022][  0]LogModuleManager: Shutting down and abandoning module PakFile (4)
[2024.07.11-22.46.38:025][  0]LogModuleManager: Shutting down and abandoning module RSA (3)
[2024.07.11-22.46.38:030][  0]LogExit: Exiting.
Engine crash handling finished; re-raising signal 0 for the default handler. Good bye.
[2024-07-11 22:46:45] [LOG] REST accessed endpoint /v1/api/players OK
[2024-07-11 22:46:50] [LOG] REST accessed endpoint /v1/api/players OK
[2024-07-11 22:46:56] [LOG] REST accessed endpoint /v1/api/players OK
[2024-07-11 22:47:01] [LOG] REST accessed endpoint /v1/api/players OK
[2024-07-11 22:47:06] [LOG] REST accessed endpoint /v1/api/players OK
[2024-07-11 22:47:12] [LOG] REST accessed endpoint /v1/api/players OK
/usr/local/bin/box64: line 32:    86 Segmentation fault      (core dumped) "$BINARY_PATH" "$@"
```

**Comment by Soham-Das-afk** [comment] 2024-09-22 08:27
facing same problem
Is it solved yet?

**Comment by thijsvanloef** [comment] 2024-09-30 12:35
@Soham-Das-afk I've not been able to run into this problem again on my ARM test instance, it is worth trying out again.
Closing for now, please reopen if the issue persists

**Closed by thijsvanloef** 2024-09-30 12:35 UTC
Labels: waiting for feedback, needs more info
